version: '3'


services:
    app:
        build: .
        tty: true
        command: sh -c "python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"
        ports:
            - "8000:8000"
        volumes:
            - .:/app
        depends_on:
            db:
                condition: service_healthy

    db:
        restart: always
        image: postgres
        ports:
            - "5435:5432"

        env_file:
            -   .env

        healthcheck:
            test: ["CMD", "pg_isready", "-U", "postgres"]
            interval: 5s
            timeout: 5s
            retries: 5
        volumes:
            - pgdata:/var/lib/postgresql/data

    redis:
        image: redis
        ports:
            - '6382:6379'

    celery:
        build: .
        tty: true
        command: celery -A config worker --pool=solo -l INFO
        env_file:
            - .env
        depends_on:
            - redis
            - app

    celery_beat:
        build: .
        tty: true
        command: celery -A config beat -l info -S django
        env_file:
            - .env
        depends_on:
            - redis
            - app

volumes:
    pgdata:
